services:
  app:
    container_name: app_${APP_NAME}
    build:
        context: .
        dockerfile: Dockerfile
    image: "sse-notification-service-app"
    restart: always
    ports:
      - '${APP_PORT}:80'
  redis:
    image: redis
    restart: always
    container_name: redis_${APP_NAME}